---
- name: Disable yum-cron
  service:
    name: yum-cron
    enabled: no
    state: stopped

- name: Clean yum(1) cache
  command: /usr/bin/yum clean all

- name: Disable kernel dynamic tics
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX[ \t]*=[ \t]*"[ \t]*(.*)[ \t]*"'
    line: 'GRUB_CMDLINE_LINUX="\1 nohz=off"'
    backrefs: yes
    backup: yes
  notify:
  - update_grub_config
