---
- hosts:
    hylafax
  roles:
    - role: yum_gpg
      when: ((ansible_distribution == "CentOS" or
              ansible_distribution == "Red Hat enterprise Linux") and
             ansible_distribution_major_version == "7")
