---
- hosts:
    hylafax


  pre_tasks:
    - name: Check if we are dealing with CentOS 7
      fail:
        msg: HylaFAX Enterprise can be installed only on CentOS 7
      when:
        not ((ansible_distribution == "CentOS" or
              ansible_distribution == "Red Hat enterprise Linux") and
             ansible_distribution_major_version == "7")

    - name: Have yum(1) check sigs on locally-installed packages
      ini_file:
        path: /etc/yum.conf
        section: main
        option: localpkg_gpgcheck
        value: '1'
        backup: yes

    - name: Trust CentOS 7 key
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        fingerprint: 6341 AB27 53D7 8A78 A7C2  7BB1 24C6 A8A7 F4A8 0EB5
        state: present

    - name: Import iFAX package signing key
      rpm_key:
        key: http://repo.ifax.com/yum/RPM-GPG-KEY-iFAX
        fingerprint: 6253 2E3E 58D0 8CB8 199E  5278 8F5A 7A5B DFCA F91C
        state: present

    - name: Install iFAX repo 6.3
      yum:
        name: http://repo.ifax.com/yum/ifax-ee-6.3.rpm
        state: present

    - name: Install EPEL
      yum:
        name: epel-release
        state: present

    - name: Import EPEL 7 key
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
        fingerprint: 91E9 7D7C 4A5E 96F1 7F3E  888F 6A2F AEA2 352C 64E5
        validate_certs: no
        state: present

  tasks:
    - name: Sysupgrade
      yum:
        name: '*'
        state: latest

    - name: Install HylaFAX Enterprise
      yum:
        name: hylafax-enterprise-appliance
        state: latest

  post_tasks:
    - name: Disable yum-cron
      service:
        name: yum-cron
        enabled: no
        state: stopped

    - name: Clean yum(1) cache
      command: /usr/bin/yum clean all

    - name: Disable kernel dynamic tics -- check
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX(.*)nohz=off(.*)'
        line: ''
        backrefs: yes
      check_mode: yes
      register: grub
      failed_when: grub is changed
      ignore_errors: yes

    - name: Disable kernel dynamic tics
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX[ \t]*=[ \t]*"[ \t]*(.*)[ \t]*"'
        line: 'GRUB_CMDLINE_LINUX="\1 nohz=off"'
        backrefs: yes
        backup: yes
      when: grub is not changed
      notify:
      - update_grub_config


  handlers:
  - name: update_grub_config
    command: /sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
